Repository physicsgoddess1972/Precipitable-Water-Model, pull requests merged in 2021-06, with the labels that each got.

#20 Pmat demo xyz
  data/cool_data.csv
  data/import.conf
  data/instruments.yml
Labels: pmat-deploy

#22 Testing
  .github/workflows/main_xyz.yml
Labels: pmat-deploy, test

#23 Demo, XYZ
  .github/workflows/main_xyz.yml
Labels: pmat-deploy

#24 Demo, XYZ
  data/cool_data.csv
Labels: pmat-deploy, test

#25 Demo, XYZ
  data/cool_data.csv
Labels: pmat-deploy, test

#26 Demo, XYZ
  data/cool_data.csv
Labels: pmat-deploy, test

#28 Demo, XYZ
  data/cool_data.csv
Labels: pmat-deploy, test

#29 Demo, XYZ
  data/cool_data.csv
Labels: pmat-deploy, test

#31 Demo, XYZ
  .github/workflows/main.yml
  data/cool_data.csv
Labels: pmat-deploy, test

#32 Demo, XYZ
  .github/workflows/main.yml
Labels: pmat-deploy, test

#34 Update cool_data.csv
  data/cool_data.csv
Labels: pmat-deploy, test

#35 Demo, XYZ
  data/cool_data.csv
Labels: pmat-deploy, test

#85 Demo, XYZ
  data/cool_data.csv
  data/import.conf
  data/instruments.yml
Labels: pmat-deploy

#98 Socorro, NM
  data/cool_data.csv
  data/import.conf
  data/instruments.yml
  data/master_data.csv
Labels: automerge, pmat-deploy

#100 Socorro, NM
  data/master_data.csv
Labels: automerge, pmat-deploy

#103 Socorro, NM
  data/master_data.csv
  figs/resutts/tmp
Labels: automerge, pmat-deploy

#109 rapidcity sd
  data/cool_data.csv
  data/import.conf
  data/instruments.yml
Labels: automerge, pmat-deploy

#113 Socorro, NM
  data/cool_data.csv
Labels: automerge, pmat-deploy
